### ISSUE TITLE
Test failure on Gentoo Linux with Ruby 1.8.7

### ISSUE THREAD

**Issue by Flameeyes** [rtomayko/posix-spawn#11]
```
  1) Failure:
test_spawn_close_invalid_fd_raises_exception(PosixSpawnTest)
    [./test/test_spawn.rb:332:in `assert_process_exit_status'
     ./test/test_spawn.rb:119:in `test_spawn_close_invalid_fd_raises_exception']:
<127> expected but was
<0>.

102 tests, 320 assertions, 1 failures, 0 errors
rake aborted!
Command failed with status (1): [/usr/bin/ruby18 -I"lib" "/usr/lib64/ruby/g...]
```

**Comment by rtomayko** [comment]
Closing as stale. Please reopen if you're still seeing test failures on Gentoo.

**Comment by graaff** [comment]
I can no longer reproduce this with posix-spawn 0.3.10.

**Comment by rtomayko** [comment]
Great, thanks for verifying!
