### ISSUE TITLE
Spawn::Child fails on win32 + 1.9.2

### ISSUE THREAD

**Issue by tmm1** [rtomayko/posix-spawn#17]
Looks like `write_nonblock` fails, even though `write` works. Probably a ruby bug.

```
$ ruby -e ' require "posix-spawn"; puts POSIX::Spawn::Child.new("dir",:input=>"
").out '
c:/Ruby192/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.5.2/lib/posix/spawn/child.rb:179:in `write_nonblock': Bad file descriptor (Errno::EBADF)
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.5.2/lib/posix/spawn/child.rb:179:in `block in read_and_write'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.5.2/lib/posix/spawn/child.rb:176:in `each'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.5.2/lib/posix/spawn/child.rb:176:in `read_and_write'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.5.2/lib/posix/spawn/child.rb:108:in `exec!'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.5.2/lib/posix/spawn/child.rb:80:in `initialize'
        from -e:1:in `new'
        from -e:1:in `<main>'

$ ruby -ve 'r,w=IO.pipe; Process.spawn("dir", :in => r, :out => "file"); w.write_nonblock("test")'
ruby 1.9.2p180 (2011-02-18) [i386-mingw32]
-e:1:in `write_nonblock': Bad file descriptor (Errno::EBADF)
        from -e:1:in `<main>'
```

**Comment by rtomayko** [comment]
Closing as stale and windows support is best effort. Please reopen if there are still simple things we can do to clean this up on windows.
