### ISSUE TITLE
no /bin/sh on win32

### ISSUE THREAD

**Issue by tmm1** [rtomayko/posix-spawn#18]
```
$ ruby -e ' require "posix-spawn"; puts POSIX::Spawn::Child.new("wc -l").out '
c:/Ruby192/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.5.2/lib/posix/spawn.rb:162:i
n `spawn': No such file or directory - /bin/sh (Errno::ENOENT)
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.5.2/lib/posix/spawn.rb:162:in `spawn'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.5.2/lib/posix/spawn.rb:307:in `popen4'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.5.2/lib/posix/spawn/child.rb:105:in `exec!'
        from c:/Ruby192/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.5.2/lib/posix/spawn/child.rb:80:in `initialize'
        from -e:1:in `new'
        from -e:1:in `<main>'
```

1.9 uses some hacks internally that we should probably copy instead of always calling /bin/sh

**Comment by rtomayko** [comment]
Closing as stale.
