### ISSUE TITLE
0.3.8 support 32 bit OS ?

### ISSUE THREAD

**Issue by tshi0912** [rtomayko/posix-spawn#49]
```Shell
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:220: warning: Insecure world writable dir /home/git/gitlab/.bundle/ruby/2.0.0/bin in PATH, mode 040777
rake aborted!
/home/git/gitlab/.bundle/ruby/2.0.0/gems/posix-spawn-0.3.8/lib/posix_spawn_ext.so: wrong ELF class: ELFCLASS64 - /home/git/gitlab/.bundle/ruby/2.0.0/gems/posix-spawn-0.3.8/lib/posix_spawn_ext.so
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/posix-spawn-0.3.8/lib/posix/spawn.rb:2:in `<top (required)>'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/posix-spawn-0.3.8/lib/posix-spawn.rb:1:in `<top (required)>'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/gitlab-grit-2.6.4/lib/grit/git.rb:2:in `<top (required)>'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/gitlab-grit-2.6.4/lib/grit.rb:34:in `<top (required)>'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/gitlab_git-5.4.0/lib/gitlab_git.rb:4:in `<top (required)>'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:76:in `require'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:72:in `each'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:61:in `each'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:61:in `require'
/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.5.3/lib/bundler.rb:131:in `require'
/home/git/gitlab/config/application.rb:6:in `<top (required)>'
/home/git/gitlab/Rakefile:5:in `require'
/home/git/gitlab/Rakefile:5:in `<top (required)>'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/rake_module.rb:25:in `load'
/home/git/gitlab/.bundle/ruby/2.0.0/gems/rake-10.1.0/lib/rake/rake_module.rb:25:in `load_rakefile'
```

It seems the 0.3.8 will use the posix_spawn_ext.so which is target for 64 bit OS, how to use it on 32 bit OS/VM?

**Comment by rtomayko** [comment]
@tshi0912 Were you able to get this straightened out? It seems rubygems may have been compiling for the wrong architecture. Please reopen if this is still an issue for you.
